Optimized the scripts

diff --git a/startPdnsServer b/startPdnsServer
--- a/startPdnsServer
+++ b/startPdnsServer
@@ -1,53 +1,50 @@
 #!/bin/bash
 
 #Check if db.sqlite file exists in pdns config directory
-checkIfPdnsDatabaseExist
+databaseFile="${PDNS_CONFIG_DIR_PATH}db.sqlite"
 
-
-# If the exit code from databaseExits is 1 it means that db.sqlite doesn't exist in pdns config directory.
-databaseExists=$?
-
-# Exit from this script if the exist code of the last command is 1
-if [[ $databaseEists -eq 1 ]]; then
-	echo "[ERROR]: Can not start pdns without database!"
-	exit 1
+if [ ! -e ${databaseFile} ]; then
+       	echo "SQLite atabase doesn't exist in ${PDNS_CONFIG_DIR_PATH} directory! Do you want to create it? [y/n]"
+       	read CREATE_DB
+        if [[ ${CREATE_DB} == 'y' || ${CREATE_DB} == 'yes' || ${CREATE_DB} == 'Y' || ${CREATE_DB} == 'YES' ]]; then
+               	touch ${PDNS_CONFIG_DIR_PATH}db.sqlite
+	else
+		echo "[ERROR]: Can not start pdns without database!"
+		exit 1
+	fi
 fi
 
-# Check if pdns.conf file exists in pdns config directory
-checkIfPdnsConfExist
 
 # If the exit code in pdnsConfFileExists is 1 it means that pdns.conf doesn't exist in pdns config directory.
-pdnsConfFileExists=$?
+pdnsConfFile="${PDNS_CONFIG_DIR_PATH}pdns.conf"
 
-if [[ $pdnsConfFileExists -eq 1 ]]; then
+if [[ ! -e ${pdnsConfFile} ]]; then
+	echo "[WARN]: Power DNS configuration file doesn't exist, create it after re-run this command to start the server"
         echo "[ERROR]: Can not start pdns without config file!"
         exit 1
 fi
 
-# Check if sqliteschema.sql file exists in pdns config directory
-checkIfPdnsSqliteSchemaExist
+# Get the number of tables in the database
+numberOfTablesInDb=$(sqlite3 ${PDNS_CONFIG_DIR_PATH}db.sqlite .tables | wc -w)
 
-# If the exit code from checkIfPdnsSqliteSchemaExist is 1 it means that sqliteschema.sql doesn't exist in pdns config directory.
-pdnsSqliteSchemaExists=$?
+# Check if db was intialized
+#dbWasInitialized=$([ ${numberOfTablesInDb} -gt 0 ])
 
-if [[ $pdnsSqliteSchemaExists -eq 1 ]]; then
-        echo "[ERROR]: Can not start pdns without sqlite schema file!"
-        exit 1
-fi
+if [ ${numberOfTablesInDb} -eq 0 ]; then
+	# Check for sqlite schema and then initialize it
+	pdnsSqliteSchemaFile="${PDNS_CONFIG_DIR_PATH}sqliteschema.sql"
 
-# Check if the Data Base schema was initialized
-checkIfDbWasInitialized
-
-# If the exit code in checkIfDbWasInitialized is 1 it means that the database was not initialized
-dbWasInitialized=$?
-
-if [[ dbWasInitialized -eq 1 ]]; then
-	
-	echo "[INFO]: Intializing db.."
-	# Initialize the data base
-	cat ${PDNS_PATH}sqliteschema.sql | sqlite3 ${PDNS_PATH}db.sqlite 
+	if [ ! -e ${pdnsSqliteSchemaFile}  ]; then
+        	echo "[WARN]: Sqlite schema file does not exist and the database is not initialized!"
+        	echo "[ERROR]: Can not start pdns without having the database initilizaed.."
+	        exit 1
+	else
+		echo "[INFO]: Intializing db.."
+	        # Initialize the data base
+        	cat ${pdnsSqliteSchemaFile} | sqlite3 ${databaseFile}
+	fi
 fi
 
 #Run the command to start the pdns server
 echo "[INFO]: Starting Power DNS Server.."
-$PDNS_START_COMMAND
+$PDNS_RUN_COMMAND
